/*
-- Query: SELECT * FROM listing_tab
LIMIT 0, 1000

-- Date: 2021-11-10 22:33
*/
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (5,'$TSLA$',150000,1,1,'Tesla, Inc. is an American electric vehicle and clean energy company based in Palo Alto, California, United States. Tesla designs and manufactures electric cars, battery energy storage from home to grid-scale, solar panels and solar roof tiles, and related products and services.',11,1,15,5,1636384939,1636389571);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (25,'Tesla Model S Plaid',49900000,5,5,'With the longest range and quickest acceleration of any electric vehicle in production, Model S Plaid is the highest performing sedan ever built. All Model S powertrains, with updated battery architecture, are capable of back-to-back, consistent 1/4 mile r',0,1,7,15,1636385795,1636385795);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (35,'iPhone 13 Pro Max 1TB',262900,4,5,'Oh. So. Pro. A dramatically more powerful camera system. A display so responsive, every interaction feels new again. The world’s fastest smartphone chip. Exceptional durability. And a huge leap in battery life. Let’s Pro. Super Retina XDR display with ProM',19,1,2,25,1636386106,1636386106);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (45,'Apple Watch Series 7',64900,97,99,'The aluminium case is lightweight and made from 100 per cent recycled aerospace-grade alloy.The Sport Band is made from a durable yet surprisingly soft high-performance fluoroelastomer, with an innovative pin-and-tuck closure.',19,1,2,25,1636386440,1636386440);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (55,'Apple iPad Pro 2TB',351900,99,99,'Faster performance and graphics. The 8‑core CPU of the Apple M1 chip delivers up to 50 per cent faster performance. And the M1 chip has an 8‑core GPU in a class of its own, providing up to 40 per cent faster graphics performance to iPad Pro. So you can bui',19,1,2,25,1636386800,1636386800);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (65,'Apple AirPods Pro 3',26900,999,999,'AirPods are lightweight and offer a contoured design. They sit at just the right angle for comfort and to better direct audio to your ear. The stem is 33 per cent shorter than AirPods (2nd generation) and includes a force sensor to easily control music and calls.',19,1,2,25,1636388115,1636388115);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (75,'MacBook Pro 16 M1 MAX',524900,999,999,'Supercharged for pros. Buy now. With the blazing-fast M1 Pro or M1 Max chip. Up to 21 hr battery life. 1080p FaceTime HD camera. Liquid Retina XDR display. Touch ID. HDMI port.',19,1,2,25,1636388261,1636388261);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (85,'Pro Display XDR',1037700,42,45,'32-inch Retina 6K. Astonishing colour accuracy. Super-wide viewing angle. And Extreme Dynamic Range.',19,1,2,25,1636388373,1636388373);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (95,'Tesla Model X Plaid',52200000,4,5,'With the most power and quickest acceleration of any SUV, Model X Plaid is the highest performing SUV ever built. All Model X powertrains, with updated battery architecture, can deliver instant torque at any speed. Model X platforms unite powertrain and battery technologies for unrivaled performance, range and efficiency. New module and pack thermal architecture allows faster charging and gives you more power and endurance in all conditions.',11,1,7,15,1636388647,1636388749);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (105,'ROG Strix RTX™ 3090',220000,2,2,'NVIDIA Ampere Streaming Multiprocessors: The building blocks for the world’s fastest, most efficient GPU, the all-new Ampere SM brings 2X the FP32 throughput and improved power efficiency. 2nd Generation RT Cores: Experience 2X the throughput of 1st gen RT Cores, plus concurrent RT and shading for a whole new level of ray tracing performance. 3rd Generation Tensor Cores: Get up to 2X the throughput with structural sparsity and advanced AI algorithms such as DLSS. Now with support for up to 8K resolution, these cores deliver a massive boost in game performance and all-new AI capabilities.',22,1,1,35,1636390001,1636390058);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (115,'ROG Swift PG65UQ',499900,10,10,'ROG Swift PG65 Big Format Gaming Display with NVIDIA® G-SYNC™- 65” 4K HDR( 3840 X 2160), 120Hz+, Ultra-low latency, NVIDIA SHIELD™',22,1,1,35,1636390198,1636390198);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (125,'ROG RAMPAGE VI EXTREME OMEGA',148800,10,10,'Intel X299 EATX gaming motherboard LGA 2066 for Intel Core X-Series processors, with ROG DIMM.2, DDR4 4266MHz , onboard 802.11ac Wi-Fi, 10Gbps LAN, USB 3.1 Gen 2, SATA, Quad M.2 and Aura Sync RGB lighting',22,1,1,35,1636390396,1636390396);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (135,'ROG G35CG',599900,10,10,'Compete at a new level with a tournament-ready gaming desktop built to deliver an exhilarating esports experience with Windows 10 Home. Up to an NVIDIA® GeForce RTX™ 3090 graphics card amps up your frames per second to make fast-paced gaming silky smooth. A powerful 11th Gen Intel® Core™ i9 CPU accelerates content creation and can even be overclocked with an AI-enhanced system that makes overclocking easier for everyone. The GT35\'s high end performance is bolstered by a cooling-focused, multi-chambered chassis design and liquid cooling system. Aura Sync accents and Keystone II technology deepen the customization options, allowing it to truly become the perfect machine for every gamer.',22,1,1,35,1636390556,1636390556);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (145,'Classic Handbag Lambskin Black',1319000,8,10,'The CHANEL iconic bag, a symbol of elegance and luxury. Discover The CHANEL Classic Handbag on the official website or in your CHANEL boutique. Icons of CHANEL.',22,1,4,45,1636391577,1636391577);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (155,'Classic Handbag Lambskin White',1319000,10,10,'The CHANEL iconic bag, a symbol of elegance and luxury. Discover The CHANEL Classic Handbag on the official website or in your CHANEL boutique. Icons of CHANEL.',22,1,4,45,1636391700,1636391700);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (165,'Small Vanity Case Beige & Black',888800,10,10,'The CHANEL iconic bag, a symbol of elegance and luxury. Discover The CHANEL Classic Handbag on the official website or in your CHANEL boutique. Icons of CHANEL. Beech Wood, Calfskin & Gold-Tone Metal. Beige & Black',22,1,4,45,1636392196,1636392272);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (175,'Chanel N°5',115000,10,10,'In 1921, Gabrielle Chanel turned the codes of perfumery upside down and created N°5. A radical creation that revolutionised the traditions of its era. A design piece turned icon whose bottle and label are immediately recognizable.\nN°5 celebrates 100 years of fame in 2021. To mark the occasion and in honor of the holiday season, CHANEL is offering a calendar unlike any other, inspired by the signature silhouette of the N°5 perfume bottle. This collector\'s item is comprised of 27 boxes numbered 5 to 31, each of which contains a full-size fragrance or makeup product, miniature, or other surprise marked with Gabrielle Chanel\'s lucky number. A piece to treasure for years to come.',22,1,8,45,1636392381,1636392410);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (185,'Chanel ROUGE ALLURE',5600,97,99,'LIMITED EDITION - N°5 HOLIDAY 2021 COLLECTION LUMINOUS INTENSE LIP COLOUR',22,1,8,45,1636392513,1636392513);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (195,'Aeron - Graphite',240000,30,30,'Aeron Remastered is the perfect marriage of performance and design.Our best-selling office chair still defines expectations for ergonomic comfort more than 20 years after its debut. Comes in Three Sizes Small, Medium, or Large, Aeron’s got your back',21,1,6,55,1636393131,1636393131);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (205,'Embody Chair - Sync Black',252900,30,30,'You feel Embody’s Pixelated Support™ the moment you sit down— a sense that you are floating, yet perfectly balanced. The seat distributes your weight evenly while supporting your body’s micro-movements. The narrow backrest allows you to move freely and naturally as it automatically adjusts to support a full range of seated postures.By reducing seated pressure and encouraging freedom of movement, Embody allows blood and oxygen to flow more freely, which helps keep you focused. Form doesn’t just follow function with Embody. Function is on full display.',21,1,6,55,1636393301,1636393301);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (215,'McSpicy',700,94,100,'If you’re one of those people who like your chicken big on spiciness, this is the sandwich for you. A thick, juicy cutlet of chicken thigh and drum sits fiery hot on a bed of crunchy lettuce between toasted sesame seed buns – shiok!',34,1,0,565,1636546379,1636546379);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (225,'Chicken McCrispy® (6pc)',840,100,100,'Even more crispy, juicy, tender chunks of chicken for you to sink your teeth into. Share it with friends and family, or simply have the entire bucket to yourself—who could blame you?',34,1,0,565,1636546482,1636546482);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (235,'Buttermilk Crispy Chicken',695,100,100,'Crispy whole-muscle chicken thigh flavoured with buttermilk packed in a glazed burger bun. Served with white cheddar cheese, romaine lettuce, black pepper mayo; and topped with grilled pineapple rings and crisp purple cabbage.In short, perfection in every bite!',34,1,0,565,1636546573,1636546573);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (245,'Evian Natural Mineral Water',350,100,100,'Meet evian+, a sparkling mineral enhanced drink made with the natural spring water you know and love, but enhanced with magnesium and zinc',31,1,0,505,1636547738,1636547738);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (255,'BE@RBRICK Basquiat 1000%',120000,1,1,'Dimensions: 1000% height 70cm',3,1,12,475,1636547976,1636547976);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (265,'LEGO Starwars Millenium Falcon',119000,2,2,'The ultimate LEGO® Star Wars Millennium Falcon has landed! With 7,500 elements, Han Solo\'s super-fast Corellian ship is crammed with the coolest details and fun features. Marvel at the intricate hull detailing, sensor dish, upper and lower quad laser cannons, 7 landing legs, lowering boarding ramp and hidden blaster cannon. Seat up to 4 minifigures in the cockpit with detachable canopy and remove the outer panels to reveal the highly detailed interior. The main hold has seating for the minifigures, a Dejarik holographic game, engineering station with a turning seat for a minifigure, and a doorway build with passageway decoration. Make your way to the rear compartment to monitor the hyperdrive from the console. There\'s also a hidden floor compartment, 2 escape pod hatches and an access ladder to the gunnery station seat and a detachable hull panel with a fully rotating quad laser cannon. Display the Millennium Falcon alongside your favorite sets for the perfect collector\'s item… and whe',7,1,12,475,1636548167,1636548167);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (275,'Off-White Galaxy Brush Zipper Hoodie',60000,10,10,'Off-White',10,1,3,395,1636548395,1636548761);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (285,'Nike Air Jordan 1 Retro High OG Pro',20000,2,2,'Cushioning, Slip-resistant, Wearable, Wrapping, Supportive',15,1,3,385,1636548892,1636548892);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (295,'Superman Dog costume',2000,20,20,'So cuteeeeeeee',20,1,5,365,1636549078,1636549078);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (305,'Sushi Cat costume',2000,20,20,'So cuteeeeeeee',20,1,5,365,1636549191,1636549191);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (315,'Solid Wood Dining Table',1999999,2,2,'Natural wood obtained from the forests, having a consistent composition of material throughout its body without hollow gaps. Strong, durable, and resistant.',2,1,6,355,1636550080,1636550080);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (325,'IKEA x ROG MATCHSPEL',25900,20,20,'MATCHSPEL gaming chair helps you play at the top of your game. The whole body enjoys nice support and you can adjust the height of the chair, neck and armrests to sit really comfy when the game begins.',38,1,6,575,1636550317,1636550317);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (335,'VINTER 2021',12900,45,45,'The perfect choice for those who want a really tall and full-bodied Christmas tree. This tree is guaranteed needle-free and takes up little storage space. Just put it in its spot and start decorating.',38,1,6,575,1636550686,1636550739);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (345,'Level 1000 Collector\'s Aegis of Champions',999999,1,1,'All Battle Pass owners who reach Battle Level 1000 are invited to receive The International 2016 Collector\'s Aegis, an exclusive 1/5th-scale, bronze-plated alloy replica of the famed champion\'s prize.',25,1,9,305,1636550924,1636550924);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (355,'Crysis 3',4990,10,10,'Crysis 3 is a 2013 first-person shooter video game developed by Crytek and published in 2013 by Electronic Arts. It is the third and final main game of the Crysis series, a sequel to the 2011 video game Crysis 2. The multiplayer portion of the game was developed by Crytek UK.',8,1,9,305,1636551062,1636551062);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (365,'Family Hub™ Multi Door, 550L',450000,10,10,'Manage your groceries efficiently with View Inside app',8,1,10,585,1636551497,1636551547);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (375,'EcoBubble™, 9Kg, Washer Dryer',115000,30,30,'Intuitive Display with AI Control. Hygiene Steam. EcoBubble™',8,1,10,585,1636551671,1636551671);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (385,'QN900A Neo QLED 8K 85\'',2824000,5,5,'The powerful evolution of Neo QLED 8K comes with a backlight dimming technology that controls our proprietary Quantum Mini LEDs with perfect precision. Witness unimaginable details expressed in both the darkest black to the purest white with x1.5 more lighting zones than normal Quantum Matrix Technology.',8,1,10,585,1636551802,1636551802);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (395,'TI11 Tickets',88888,5,5,'Leaked frotn row tickets',5,1,13,255,1636552080,1636552080);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (405,'五月天 JUST ROCK IT Tickets',66600,5,5,'Mayday Just Rock It!!! BLUE in Singapore is proactively being rescheduled to 03 December 2022 (Saturday) in view of the latest authorities advisory.',5,1,13,245,1636552374,1636552374);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (415,'SUPREME RAWLINGS CHROME MAPLE WOOD BAS',50000,1,1,'100% Authentic',15,1,14,235,1636552554,1636552554);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (425,'SUPREME Brick',39900,1,1,'100% Authentic',15,1,10,235,1636552705,1636552745);
INSERT INTO `` (`l_item_id`,`item_name`,`item_price`,`item_quantity`,`item_stock`,`item_description`,`item_location`,`item_status`,`item_category`,`l_seller_id`,`listing_ctime`,`listing_mtime`) VALUES (435,'Penthouse for sale',2000000000,1,1,'In the living area, the high ceilings and the view of the city were enhanced by to the use of communicating spaces between the dining area and the living room. Elements from the recent Milano collectioncreate an atmosphere of modern luxury, interacting with warm green, beige and brown colours. In the sleeping area the atmosphere is more intimate, the furniture from the Milano collection are proposed in light beige tones in contrast with the darker colours of the walls. The Milano bed upholsterd in fabric becomes the centre piece of the bedroom, a comfortable piece from which one can admire the fascinating surrounding landscape.',22,1,16,205,1636552972,1636552972);
