version: '3'

services:
  server:
    image: registry.heroku.com/tic2601-t11/web
    container_name: tic2601-server
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - ".:/app"

  # database:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.db
  #   container_name: tic2601-db
  #   environment: 
  #     - MYSQL_ROOT_HOST=${TEST_DB_HOST} 
  #     - MYSQL_USER=${TEST_DB_USER}
  #     - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
  #     - MYSQL_DATABASE=${TEST_DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${TEST_DB_PASSWORD}
  #   ports:
  #     - 3305:3306
  #   volumes:
  #     - tic2601-data:/var/lib/mysql

  # pma:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - database
  #   ports:
  #     - 5003:80
  #   environment:
  #     - 'PMA_HOST=database'
  #     - 'PMA_PORT=3306'
  #     - MYSQL_USER=${TEST_DB_USER}
  #     - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
  #   container_name: tic2601-server-pma

# persisted storage
volumes:
  tic2601-data: