
version: '3'

services:
  web:
    container_name: tic2601-web
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - database
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
    volumes:
      - ".:/app"
    links:
      - "database"

  database:
    image: mysql:5.7.22
    container_name: tic2601-db
    environment: 
          - MYSQL_ROOT_HOST=${TEST_DB_HOST} 
          - MYSQL_USER=${TEST_DB_USER}
          - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
          - MYSQL_DATABASE=${TEST_DB_NAME}
          - MYSQL_ROOT_PASSWORD=${TEST_DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - database_mysql:/var/lib/mysql 

# persisted storage
volumes:
  golang-docker-data: