package constant

const (
	LISTING_STATUS_ALL     = 0
	LISTING_STATUS_NORMAL  = 1
	LISTING_STATUS_SOLDOUT = 2
	LISTING_STATUS_DELETED = 3

	LISTING_CATEGORY_FOOD        = 0
	LISTING_CATEGORY_ELECTRONICE = 1
)
