package constant

const (
	ITEM_STATUS_ALL     = 0
	ITEM_STATUS_NORMAL  = 1
	ITEM_STATUS_SOLDOUT = 2
	ITEM_STATUS_DELETED = 3

	ITEM_CATEGORY_FOOD        = 0
	ITEM_CATEGORY_ELECTRONICS = 1

	SHIPPING_TYPE_MAIL    = 0
	SHIPPING_TYPE_COURIER = 1
	SHIPPING_TYPE_COD     = 2

	PAYMENT_TYPE_WALLET        = 0
	PAYMENT_TYPE_CREDIT_CARD   = 1
	PAYMENT_TYPE_BANK_TRANSFER = 2
	PAYMENR_TYPE_INSTALMENT    = 3
	PAYMENT_TYPE_CASH          = 4
)
