package constant

const (
	WALLET_STATUS_ACTIVE   = 0
	WALLET_STATUS_INACTIVE = 1
	WALLET_STATUS_DISABLED = 2

	TRANSACTION_TYPE_TOPUP    = 0
	TRANSACTION_TYPE_PURCHASE = 1
	TRANSACTION_TYPE_SALES    = 2
)
