package constant

const (
	WALLET_STATUS_ACTIVE   = 0
	WALLET_STATUS_INACTIVE = 1
	WALLET_STATUS_DISABLED = 2

	TRANSACTION_STATUS_SUCCESS = 0
	TRANSACTION_STATUS_PENDING = 1
	TRANSACTION_STATUS_FAIL    = 2
)
